# Site settings
title: Pandas y HDFS con DataFrame Dask
description: "Pandas y HDFS con DataFrame Dask"
author:
  name: "Enrique Peinado-Renzo Cerr√≥n-Edgar Huaranga"
  email: "epeinador@uni.pe-rcerront@uni.pe-edgar.huaranga@uni.pe"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
